### ISSUE TITLE
SG-Website update

### ISSUE THREAD

**Issue by vanshbothra** [sg-au/sg-main#26]
Edits needed on the sg website:-
1. In the home page :- Add samarths photo, “insert link here” - link to be inserted, change ticketing service as shown as upcoming
2. ⁠Update council members and HoR members list
3. ⁠In HoR committees, Registration Enhancement committee and Alumni Relations Committee are not hyperlinks to their mandates. The page also doesn’t contain Statutory Review Committee and FinAid Committee
4. ⁠Add hyper links to different ministry pages from Cabinet-About page
5. ⁠Update the team members, team names and their pictures of all ministries
6. ⁠Update projects list in Techmin page with all the projects
7. ⁠Shorten the effects duration for texts to appear faster
8. ⁠Update helpful resources to add more information than CWC and OLS

**Comment by Avi54** [comment]
- Have not done 8 as don't have information to add as of now
- List of team members for different ministries not added (don't have list)
- Added a platform button to the home page header part below Ashoka University text
